spring:
  application:
   name: finfox
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/finfox}
  ai:
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.finfox: DEBUG
    
finfox:
  jwt:
    secret: ${JWT_SECRET:verysecretkeyMustBeLongerThan256bitsToAvoidErrorsInProductionEnv}
    expiration-ms: 86400000 # 24 hours
